### PR TITLE
[WIP] TypeClassResolutionTest for code snippets (2)

### PR DESCRIPTION
**Pull request by rachelcarmena**
## Changes

This pull request would discard #57. That's the reason why it's a pull request on `master` branch.

It has 2 commits:

*    The fist commit comes from #57 + remove changes in `docs` and `testing-plugin` which were failing. **Note**: It keeps the author from #57.
*    The second commit extracts the compilation code to relocate classes and fix the test added to show the failure in #57.

The test which was added by @jansorg to help me to debug the problems in #57 is passing now but I don't have knowledge enough to change `testSyntheticResolution` in the same way.

## Details

Initial problems like:

```
 * What went wrong:
Execution failed for task ':testing-plugin:compileKotlin'.
> Compilation error. See log for more details
```

which appear in #57 have been solved.

The problem:

```
e: java.lang.ClassCastException: org.jetbrains.kotlin.idea.KotlinFileType 
cannot be cast to org.jetbrains.kotlin.com.intellij.openapi.fileTypes.FileType
```

was solved when relocating some classes:

```
relocate 'org.jetbrains.kotlin.com.intellij', 'com.intellij'
```

That's the reason why the source code was moved to another library to be able to relocate classes before using it in `idea-plugin`.

Then, the problem was:

```
e: java.lang.IllegalStateException: @NotNull method 
com/intellij/openapi/roots/ProjectFileIndex.getInstance must not return null
```

because the "environment" to compile source code is created in a `MockProject` when using `CodeInsightFixtureTestCase` and it's not possible to get an instance from a `MockProject`:

```
  @NotNull
  static ProjectFileIndex getInstance(@NotNull Project project) {
    return ServiceManager.getService(project, ProjectFileIndex.class);
  }
```

Source: `com.intellij.openapi.roots.ProjectFileIndex` com.jetbrains.ideaIC

## Next steps

Try to fix the ignored test `TypeClassResolutionTest` from these changes and research the use of `CodeInsightFixtureTestCase` and its effects when running compilations.

This is the "trace" with the use of `CodeInsightFixtureTestCase`:

1.    Load Arrow Plugin (IDEA)
2.    Start a compilation
3.    Failure

This is the "trace" without that class and with a regular test:

1.    Start a compilation
2.   Load Arrow Plugin (IDEA)
3.    Compilation
4.    Success

## Note

@jansorg , please, feel free to discard/close this pull request and to continue working on `heavy-testing` branch. I feel happy to know that I discovered the problem and some clues to continue working on it.

### CODE REVIEW

**Comment by i-walker** [comment]
Hi @rachelcarmena could you direct this PR towards`ja-heavy-testing`, so that we have a better time reviewing and accomplishing the ticket, because compiling the Source code is one among other subsequent steps we still need to accomplish for that PR to work.

**Comment by rachelcarmena** [comment]
> Hi @rachelcarmena could you direct this PR towards`ja-heavy-testing`, so that we have a better time reviewing and accomplishing the ticket, because compiling the Source code is one among other subsequent steps we still need to accomplish for that PR to work.

Thanks @i-walker !! It's still WIP, thanks!!

**Comment by raulraja** [comment]
heads up:
Screenshot 2019-11-12 at 01 03 33

**Comment by rachelcarmena** [comment]
> heads up:
> Screenshot 2019-11-12 at 01 03 33

Thanks, solved!

**Comment by rachelcarmena** [comment]
@jansorg, I've added 2 more commits:
- Solving conflicts with `master` branch
- Add `PreviousLightTestSyntax` for keep it working with the new commits on `master` branch: 
  - https://github.com/arrow-kt/arrow-meta/commit/c4d502b683175aae5f2f1f5fbf84a6fa06ee33ed
  - https://github.com/arrow-kt/arrow-meta/commit/2a4aee7e05b247cee89285151fb23820ba26d97e
  - https://github.com/arrow-kt/arrow-meta/commit/c81a7082d4c13cd435d11f03c45f58ead5218666

**Comment by rachelcarmena** [comment]
Documentation was failing with the last merge because of removing:

```
compile project(':compiler-plugin')
```

from `docs/build.gradle`.

**Reason**: the new `build.gradle` for `idea-plugin` excludes Kotlin stdlib for all the dependencies:

```
exclude group: "org.jetbrains.kotlin", module: "kotlin-stdlib"
```

So it was solved adding Kotlin stdlib as dependency in `docs/build.gradle`.

**Comment by raulraja** [comment]
Outdated
