### ISSUE TITLE
[BUG] NoSuchMethod error on Kotlin 1.5.30 but works on 1.6.0

### ISSUE THREAD

**Issue by Sushobh** [arrow-kt/arrow-meta#1058]
Is arrow meta supposed to work on 1.5.30? I am getting NoSuchMethod error. 
java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.ir.IrBuiltIns org.jetbrains.kotlin.backend.common.extensions.IrPluginContext.getIrBuiltIns()'

But works fine 1.6.0.
Is there any workaround for this?

**Comment by raulraja** [comment]
Hi @Sushobh, Arrow meta is currently in the process of being redesigned for K2 FIR's new frontend compiler for Kotlin. 
We expect to have stable releases of meta again after 1.9 or 1.10 when FIR is stable with new APIs that target the new frontend.

As for the error you are describing, it's probably because the compiler internals changed between versions. There are currently no plans to target or backport old versions of kotlin.

If you can provide more info on what you are trying to do, I can provide more info on how to accomplish with the current state of the kotlin compiler.

There are some other versions of meta https://mvnrepository.com/artifact/io.arrow-kt/arrow-meta but can't recall if any work on 1.5.30

**Comment by Sushobh** [comment]
Thanks Raul, that was informative. One more question , i thought the current Arrow meta library is targeting the latest kotlin IR. Is the kotlin IR going to change again?

**Comment by raulraja** [comment]
The IR formats keep adapting to new features, such as multiple context receivers. The actual API for mutating and transforming IR nodes hasn't changed much, but often between versions, we see methods in the plugin context and similar getting relocated to refine the API. So IR backend is stable as a format, but the compiler internals around it is not.
As part of the redesign of meta, we are trying to bring two main features.

1. A compile-time reflection library that implements the `KClass` and similar interfaces from kotlin reflection but gets its information about declarations expanded at compile time.

2. User-level macros with an AST that is not the compiler's internal IR nodes. Working directly with IR has the disadvantage that we have no control over the API, and then run into issues like yours where some compiler internals changed, but a compiler plugin author should not have cared about that change.

We are currently in flux because there is no stable compiler plugin API either, but that is supposed to change sometime in 1.9 or 1.10 🤞 . At that point and in this potentially bright future, compiler plugins will be able to run in the IDE analysis phase, and you can get real-time error highlighting from your plugin. I've already seen this working hacking the current FIR support, and it's a game changer, but maybe a year or more to be able to release something stable with the compiler around metaprogramming in general.

**Comment by Sushobh** [comment]
Cool, i will be looking forward to a stable compiler plugin api.
